name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  path: ^1.9.1
  get: ^4.7.2
  carousel_slider: ^5.1.1
  firebase_core: ^4.1.0
  lottie: ^3.3.2
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  firebase_ai: ^3.2.0
  firebase_app_check: ^0.4.0+1
  connectivity_plus: ^7.0.0
  flutter_ai_toolkit: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  mockito: ^5.5.1
  flutter_launcher_icons: ^0.14.4
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/fonts/
    - assets/icon/
  fonts:
    - family: Libertinus_discursive
      fonts:
        - asset: assets/fonts/LibertinusSans_discursive-ExtraLight.ttf
        - asset: assets/fonts/LibertinusSans_discursive-Light.ttf
        - asset: assets/fonts/LibertinusSans_discursive-Regular.ttf
          weight: 500
    - family: Libertinus
      fonts:
        - asset: assets/fonts/LibertinusSans-Regular.ttf
          weight: 500 
        - asset: assets/fonts/LibertinusSans-Italic.ttf
        - asset: assets/fonts/LibertinusSans-Bold.ttf
          weight: 700
flutter_launcher_icons:
  image_path: "assets/icon/logo_android.png"

  android: "launcher_icon"
  min_sdk_android: 21 
  ios: true
  remove_alpha_ios: true

